# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider release for DockerHub and AliyunHub
on:
  release:
    types:
    - published
jobs:
  dockerhub-release-assests:
    name: Release Kubespider
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: cesign/kubespider:${{  github.ref_name }}

  acr-release-assests:
    name: Release Kubespider
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: |
          linux/amd64
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/kubespider:${{  github.ref_name }}
