# Copyright 2023 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Release Chrome Extension
on:
  push:
    tags:
      - "extension-v*.*.*"
jobs:
  Release-Extension:
    name: Release Kubespider Chrome Extension
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Extract Release Tag and Commit SHA
      id: vars
      shell: bash
      run: |
        echo "release_tag=$(echo ${GITHUB_REF#refs/tags/extension-})" >> $GITHUB_ENV

    # pack zip and read manifest, can be reused in the following steps
    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: 'chrome-extension'
        zipFilePath: 'chrome-extension-${{env.release_tag}}.zip'

    - name: Upload Release Manifests
      uses: softprops/action-gh-release@v1
      with:
        name: Chrome Extension ${{env.release_tag}}
        files: |
          chrome-extension-${{env.release_tag}}.zip
